#!/usr/bin/env bash
set -euo pipefail

WORKSPACE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SNAPSHOT_FILE="$WORKSPACE_DIR/KERNEL_STATE_SNAPSHOT.md"

source "$HOME/.cargo/env" 2>/dev/null || true

commit_hash=$(git -C "$WORKSPACE_DIR" rev-parse HEAD)
branch=$(git -C "$WORKSPACE_DIR" branch --show-current)
commit_info=$(git -C "$WORKSPACE_DIR" log -1 --pretty=format:'%H %ci %an %s')
status=$(git -C "$WORKSPACE_DIR" status --porcelain)
clean_status="clean"
if [[ -n "$status" ]]; then
  clean_status="dirty"
fi

kernel_files=(
  src/sovereign_kernel.rs
  src/kernel.rs
  src/sovereign_bus.rs
  src/crypto_pipeline.rs
  src/interface_discovery.rs
  src/hal_output.rs
  src/operator_interface.rs
  src/tlbss_integrity_engine.rs
)

kernel_files_present=()
for f in "${kernel_files[@]}"; do
  if [[ -f "$WORKSPACE_DIR/$f" ]]; then
    kernel_files_present+=("$f")
  fi
done

cargo_check_output=""
if command -v cargo >/dev/null 2>&1; then
  cargo_check_output=$(cd "$WORKSPACE_DIR" && cargo check --workspace 2>&1 || true)
else
  cargo_check_output="cargo not installed"
fi

repo_name=$(basename "$WORKSPACE_DIR")
commit_line="- Commit: \`$commit_hash\`"
branch_line="- Branch: \`$branch\`"
repo_line="- Repository: \`$repo_name\`"
commit_info_line="- Commit info: \`$commit_info\`"
working_tree_line="- Working tree: \`$clean_status\`"
host_info="- Host: \`$(uname -a | tr -s ' ')\`"
rustc_info="- Rust toolchain: \`$(command -v rustc >/dev/null 2>&1 && rustc --version || echo 'rustc not installed')\`"
cargo_info="- Cargo: \`$(command -v cargo >/dev/null 2>&1 && cargo --version || echo 'cargo not installed')\`"

{
  cat <<'EOF'
# Kernel State Snapshot

> Generated by `scripts/update_kernel_snapshot.sh`.
> Run this script anytime kernel implementation changes to refresh the snapshot.

## Repository State
EOF
  printf '%s\n' "$repo_line"
  printf '%s\n' "$branch_line"
  printf '%s\n' "$commit_line"
  printf '%s\n' "$commit_info_line"
  printf '%s\n' "$working_tree_line"
  cat <<'EOF'

## Kernel Source Files

The following kernel-related source files are currently present:
EOF
  for f in "${kernel_files_present[@]}"; do
    printf '%s\n' "- \`$f\`"
  done
  cat <<'EOF'

## Build Environment
EOF
  printf '%s\n' "$host_info"
  printf '%s\n' "$rustc_info"
  printf '%s\n' "$cargo_info"
  cat <<'EOF'

## Cargo Check Result

`cargo check --workspace`
EOF
  printf '%s\n' "$cargo_check_output" | sed 's/^/    /'
  cat <<'EOF'

## Notes

- This file is intended to be refreshed whenever kernel implementation changes.
- It is a living snapshot of the repository, build state, and kernel module list.
EOF
} > "$SNAPSHOT_FILE"
